# Generated by Django 6.1.1 on 2026-09-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('power', models.CharField(choices=[('strength', 'Super Strength'), ('speed', 'Super Speed'), ('flying', 'Flying'), ('telepathy', 'Telepathy'), ('invisibility', 'Invisibility'), ('healing', 'Healing'), ('technology', 'Advanced Technology'), ('magic', 'Magic'), ('time_travel', 'Time Travel'), ('energy', 'Energy Manipulation'), ('other', 'Other')], default='other', max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('avengers', 'Avengers'), ('justice_league', 'Justice League'), ('xmen', 'X-Men'), ('guardians', 'Guardians'), ('fantastic_four', 'Fantastic Four'), ('other', 'Other')], default='other', max_length=200)),
                ('real_name', models.CharField(max_length=200)),
            ],
        ),
    ]
